#!/usr/bin/env python2
"""
Command line client for the progressbr web service.
"""
from __future__ import print_function
import sys
import argparse
import logging
from pbr import ProgressbrClient, RESTException


def create_wrapper(client, args):
    try:
        resp = client.create(args.range_min, args.range_max, description=args.description)
        print(resp['uuid'])
    except RESTException as e:
        print("Request error, status code: %d" % e.status_code, file=sys.stderr)
        print("Content:\n%s" % e.message, file=sys.stderr)


def update_wrapper(client, args):
    try:
        resp = client.update(args.uuid, args.n_min, args.n_max, description=args.description)
    except RESTException as e:
        print("Request error, status code %d" % e.status_code, file=sys.stderr)
        print("Content:\n%s" % e.message, file=sys.stderr)


if __name__ == "__main__":
    logging.basicConfig(level=logging.WARNING)

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-b', '--base-url', type=str, help='base url', default='https://progressbr.herokuapp.com')
    subparsers = parser.add_subparsers(help='sub-command help')

    parser_create = subparsers.add_parser('create', help='create new progress bar')
    parser_create.add_argument('-d', '--description', type=str, help='description', default=None)
    parser_create.add_argument('-k', '--private-key', type=str, help='private user key', default=None)
    parser_create.add_argument('range_min',           type=int, nargs='?', help='range min')
    parser_create.add_argument('range_max',           type=int,            help='range max')
    parser_create.set_defaults(func=create_wrapper)

    parser_update = subparsers.add_parser('update', help='update progress bar')
    parser_update.add_argument('-d', '--description', type=str, help='description')
    parser_update.add_argument('uuid',                type=str, help='progress bar identifier')
    parser_update.add_argument('n_min',           type=int, nargs='?', help='update min')
    parser_update.add_argument('n_max',           type=int,            help='update max')
    parser_update.set_defaults(func=update_wrapper)

    args = parser.parse_args()
    client = ProgressbrClient(args.base_url)
    args.func(client, args)
